def complete_sandhi(text: str):
    return (
        text\
            .replace("is","iṣ")\
            .replace("ṣt","ṣṭ")\
            .replace("sṭ","ṣṭ")\
            .replace("rn","rṇ")\
            .replace("ṛn","ṛṇ")\
            .replace("sḳ","cch")\
            .replace("dt","tt")\
            .replace("ds","ts")\
            .replace("ss","s")\
            .replace("ks","kṣ")\
            .replace("ct","kt")\
            .replace("cs","kṣ")\
            .replace("iṯ","iṣṭ")\
            .replace("ṯi","ti")\
            .replace("ṯ","st")\
            .replace("hth","gdh")\
            .replace("ht","gdh")\
            .replace("hṉv","hanv")\
            .replace("hṉm","hanm")\
            .replace("ea","aya")\
            .replace("oa","ava")\
            .replace("aia","āya")\
            .replace("aua","āva")\
            .replace("aiiai","aiyai")\
            .replace("aiiau","aiyau")\
            .replace("aiia","aiya")\
            .replace("aiiā","aiyā")\
            .replace("aiii","aiyi")\
            .replace("aiiī","aiyī")\
            .replace("aiiu","aiyu")\
            .replace("aiiū","aiyū")\
            .replace("aiiṛ","aiyṛ")\
            .replace("aiiṝ","aiyṝ")\
            .replace("aiiḷ","aiyḷ")\
            .replace("aiiḹ","aiyḹ")\
            .replace("aiie","aiye")\
            .replace("aiio","aiyo")\
            .replace("auiai","auyai")\
            .replace("auiau","auyau")\
            .replace("auia","auya")\
            .replace("auiā","auyā")\
            .replace("auii","auyi")\
            .replace("auiī","auyī")\
            .replace("auiu","auyu")\
            .replace("auiū","auyū")\
            .replace("auiṛ","auyṛ")\
            .replace("auiṝ","auyṝ")\
            .replace("auiḷ","auyḷ")\
            .replace("auiḹ","auyḹ")\
            .replace("auie","auye")\
            .replace("auio","auyo")\
            .replace("aiai","ayai")\
            .replace("aiau","ayau")\
            .replace("aia","aya")\
            .replace("aiā","ayā")\
            .replace("aii","ayi")\
            .replace("aiī","ayī")\
            .replace("aiu","ayu")\
            .replace("aiū","ayū")\
            .replace("aiṛ","ayṛ")\
            .replace("aiṝ","ayṝ")\
            .replace("aiḷ","ayḷ")\
            .replace("aiḹ","ayḹ")\
            .replace("aie","aye")\
            .replace("aio","ayo")\
            .replace("āiai","āyai")\
            .replace("āiau","āyau")\
            .replace("āia","āya")\
            .replace("āiā","āyā")\
            .replace("āii","āyi")\
            .replace("āiī","āyī")\
            .replace("āiu","āyu")\
            .replace("āiū","āyū")\
            .replace("āiṛ","āyṛ")\
            .replace("āiṝ","āyṝ")\
            .replace("āiḷ","āyḷ")\
            .replace("āiḹ","āyḹ")\
            .replace("āie","āye")\
            .replace("āio","āyo")\
            .replace("iiai","iyai")\
            .replace("iiau","iyau")\
            .replace("iia","iya")\
            .replace("iiā","iyā")\
            .replace("iii","iyi")\
            .replace("iiī","iyī")\
            .replace("iiu","iyu")\
            .replace("iiū","iyū")\
            .replace("iiṛ","iyṛ")\
            .replace("iiṝ","iyṝ")\
            .replace("iiḷ","iyḷ")\
            .replace("iiḹ","iyḹ")\
            .replace("iie","iye")\
            .replace("iio","iyo")\
            .replace("īiai","īyai")\
            .replace("īiau","īyau")\
            .replace("īia","īya")\
            .replace("īiā","īyā")\
            .replace("īii","īyi")\
            .replace("īiī","īyī")\
            .replace("īiu","īyu")\
            .replace("īiū","īyū")\
            .replace("īiṛ","īyṛ")\
            .replace("īiṝ","īyṝ")\
            .replace("īiḷ","īyḷ")\
            .replace("īiḹ","īyḹ")\
            .replace("īie","īye")\
            .replace("īio","īyo")\
            .replace("uiai","uyai")\
            .replace("uiau","uyau")\
            .replace("uia","uya")\
            .replace("uiā","uyā")\
            .replace("uii","uyi")\
            .replace("uiī","uyī")\
            .replace("uiu","uyu")\
            .replace("uiū","uyū")\
            .replace("uiṛ","uyṛ")\
            .replace("uiṝ","uyṝ")\
            .replace("uiḷ","uyḷ")\
            .replace("uiḹ","uyḹ")\
            .replace("uie","uye")\
            .replace("uio","uyo")\
            .replace("ūiai","ūyai")\
            .replace("ūiau","ūyau")\
            .replace("ūia","ūya")\
            .replace("ūiā","ūyā")\
            .replace("ūii","ūyi")\
            .replace("ūiī","ūyī")\
            .replace("ūiu","ūyu")\
            .replace("ūiū","ūyū")\
            .replace("ūiṛ","ūyṛ")\
            .replace("ūiṝ","ūyṝ")\
            .replace("ūiḷ","ūyḷ")\
            .replace("ūiḹ","ūyḹ")\
            .replace("ūie","ūye")\
            .replace("ūio","ūyo")\
            .replace("ṛiai","ṛyai")\
            .replace("ṛiau","ṛyau")\
            .replace("ṛia","ṛya")\
            .replace("ṛiā","ṛyā")\
            .replace("ṛii","ṛyi")\
            .replace("ṛiī","ṛyī")\
            .replace("ṛiu","ṛyu")\
            .replace("ṛiū","ṛyū")\
            .replace("ṛiṛ","ṛyṛ")\
            .replace("ṛiṝ","ṛyṝ")\
            .replace("ṛiḷ","ṛyḷ")\
            .replace("ṛiḹ","ṛyḹ")\
            .replace("ṛie","ṛye")\
            .replace("ṛio","ṛyo")\
            .replace("ṝiai","ṝyai")\
            .replace("ṝiau","ṝyau")\
            .replace("ṝia","ṝya")\
            .replace("ṝiā","ṝyā")\
            .replace("ṝii","ṝyi")\
            .replace("ṝiī","ṝyī")\
            .replace("ṝiu","ṝyu")\
            .replace("ṝiū","ṝyū")\
            .replace("ṝiṛ","ṝyṛ")\
            .replace("ṝiṝ","ṝyṝ")\
            .replace("ṝiḷ","ṝyḷ")\
            .replace("ṝiḹ","ṝyḹ")\
            .replace("ṝie","ṝye")\
            .replace("ṝio","ṝyo")\
            .replace("ḷiai","ḷyai")\
            .replace("ḷiau","ḷyau")\
            .replace("ḷia","ḷya")\
            .replace("ḷiā","ḷyā")\
            .replace("ḷii","ḷyi")\
            .replace("ḷiī","ḷyī")\
            .replace("ḷiu","ḷyu")\
            .replace("ḷiū","ḷyū")\
            .replace("ḷiṛ","ḷyṛ")\
            .replace("ḷiṝ","ḷyṝ")\
            .replace("ḷiḷ","ḷyḷ")\
            .replace("ḷiḹ","ḷyḹ")\
            .replace("ḷie","ḷye")\
            .replace("ḷio","ḷyo")\
            .replace("ḹiai","ḹyai")\
            .replace("ḹiau","ḹyau")\
            .replace("ḹia","ḹya")\
            .replace("ḹiā","ḹyā")\
            .replace("ḹii","ḹyi")\
            .replace("ḹiī","ḹyī")\
            .replace("ḹiu","ḹyu")\
            .replace("ḹiū","ḹyū")\
            .replace("ḹiṛ","ḹyṛ")\
            .replace("ḹiṝ","ḹyṝ")\
            .replace("ḹiḷ","ḹyḷ")\
            .replace("ḹiḹ","ḹyḹ")\
            .replace("ḹie","ḹye")\
            .replace("ḹio","ḹyo")\
            .replace("eiai","eyai")\
            .replace("eiau","eyau")\
            .replace("eia","eya")\
            .replace("eiā","eyā")\
            .replace("eii","eyi")\
            .replace("eiī","eyī")\
            .replace("eiu","eyu")\
            .replace("eiū","eyū")\
            .replace("eiṛ","eyṛ")\
            .replace("eiṝ","eyṝ")\
            .replace("eiḷ","eyḷ")\
            .replace("eiḹ","eyḹ")\
            .replace("eie","eye")\
            .replace("eio","eyo")\
            .replace("oiai","oyai")\
            .replace("oiau","oyau")\
            .replace("oia","oya")\
            .replace("oiā","oyā")\
            .replace("oii","oyi")\
            .replace("oiī","oyī")\
            .replace("oiu","oyu")\
            .replace("oiū","oyū")\
            .replace("oiṛ","oyṛ")\
            .replace("oiṝ","oyṝ")\
            .replace("oiḷ","oyḷ")\
            .replace("oiḹ","oyḹ")\
            .replace("oie","oye")\
            .replace("oio","oyo")\
            .replace("aiuai","aivai")\
            .replace("aiuau","aivau")\
            .replace("aiua","aiva")\
            .replace("aiuā","aivā")\
            .replace("aiui","aivi")\
            .replace("aiuī","aivī")\
            .replace("aiuu","aivu")\
            .replace("aiuū","aivū")\
            .replace("aiuṛ","aivṛ")\
            .replace("aiuṝ","aivṝ")\
            .replace("aiuḷ","aivḷ")\
            .replace("aiuḹ","aivḹ")\
            .replace("aiue","aive")\
            .replace("aiuo","aivo")\
            .replace("auuai","auvai")\
            .replace("auuau","auvau")\
            .replace("auua","auva")\
            .replace("auuā","auvā")\
            .replace("auui","auvi")\
            .replace("auuī","auvī")\
            .replace("auuu","auvu")\
            .replace("auuū","auvū")\
            .replace("auuṛ","auvṛ")\
            .replace("auuṝ","auvṝ")\
            .replace("auuḷ","auvḷ")\
            .replace("auuḹ","auvḹ")\
            .replace("auue","auve")\
            .replace("auuo","auvo")\
            .replace("auai","avai")\
            .replace("auau","avau")\
            .replace("aua","ava")\
            .replace("auā","avā")\
            .replace("aui","avi")\
            .replace("auī","avī")\
            .replace("auu","avu")\
            .replace("auū","avū")\
            .replace("auṛ","avṛ")\
            .replace("auṝ","avṝ")\
            .replace("auḷ","avḷ")\
            .replace("auḹ","avḹ")\
            .replace("aue","ave")\
            .replace("auo","avo")\
            .replace("āuai","āvai")\
            .replace("āuau","āvau")\
            .replace("āua","āva")\
            .replace("āuā","āvā")\
            .replace("āui","āvi")\
            .replace("āuī","āvī")\
            .replace("āuu","āvu")\
            .replace("āuū","āvū")\
            .replace("āuṛ","āvṛ")\
            .replace("āuṝ","āvṝ")\
            .replace("āuḷ","āvḷ")\
            .replace("āuḹ","āvḹ")\
            .replace("āue","āve")\
            .replace("āuo","āvo")\
            .replace("iuai","ivai")\
            .replace("iuau","ivau")\
            .replace("iua","iva")\
            .replace("iuā","ivā")\
            .replace("iui","ivi")\
            .replace("iuī","ivī")\
            .replace("iuu","ivu")\
            .replace("iuū","ivū")\
            .replace("iuṛ","ivṛ")\
            .replace("iuṝ","ivṝ")\
            .replace("iuḷ","ivḷ")\
            .replace("iuḹ","ivḹ")\
            .replace("iue","ive")\
            .replace("iuo","ivo")\
            .replace("īuai","īvai")\
            .replace("īuau","īvau")\
            .replace("īua","īva")\
            .replace("īuā","īvā")\
            .replace("īui","īvi")\
            .replace("īuī","īvī")\
            .replace("īuu","īvu")\
            .replace("īuū","īvū")\
            .replace("īuṛ","īvṛ")\
            .replace("īuṝ","īvṝ")\
            .replace("īuḷ","īvḷ")\
            .replace("īuḹ","īvḹ")\
            .replace("īue","īve")\
            .replace("īuo","īvo")\
            .replace("uuai","uvai")\
            .replace("uuau","uvau")\
            .replace("uua","uva")\
            .replace("uuā","uvā")\
            .replace("uui","uvi")\
            .replace("uuī","uvī")\
            .replace("uuu","uvu")\
            .replace("uuū","uvū")\
            .replace("uuṛ","uvṛ")\
            .replace("uuṝ","uvṝ")\
            .replace("uuḷ","uvḷ")\
            .replace("uuḹ","uvḹ")\
            .replace("uue","uve")\
            .replace("uuo","uvo")\
            .replace("ūuai","ūvai")\
            .replace("ūuau","ūvau")\
            .replace("ūua","ūva")\
            .replace("ūuā","ūvā")\
            .replace("ūui","ūvi")\
            .replace("ūuī","ūvī")\
            .replace("ūuu","ūvu")\
            .replace("ūuū","ūvū")\
            .replace("ūuṛ","ūvṛ")\
            .replace("ūuṝ","ūvṝ")\
            .replace("ūuḷ","ūvḷ")\
            .replace("ūuḹ","ūvḹ")\
            .replace("ūue","ūve")\
            .replace("ūuo","ūvo")\
            .replace("ṛuai","ṛvai")\
            .replace("ṛuau","ṛvau")\
            .replace("ṛua","ṛva")\
            .replace("ṛuā","ṛvā")\
            .replace("ṛui","ṛvi")\
            .replace("ṛuī","ṛvī")\
            .replace("ṛuu","ṛvu")\
            .replace("ṛuū","ṛvū")\
            .replace("ṛuṛ","ṛvṛ")\
            .replace("ṛuṝ","ṛvṝ")\
            .replace("ṛuḷ","ṛvḷ")\
            .replace("ṛuḹ","ṛvḹ")\
            .replace("ṛue","ṛve")\
            .replace("ṛuo","ṛvo")\
            .replace("ṝuai","ṝvai")\
            .replace("ṝuau","ṝvau")\
            .replace("ṝua","ṝva")\
            .replace("ṝuā","ṝvā")\
            .replace("ṝui","ṝvi")\
            .replace("ṝuī","ṝvī")\
            .replace("ṝuu","ṝvu")\
            .replace("ṝuū","ṝvū")\
            .replace("ṝuṛ","ṝvṛ")\
            .replace("ṝuṝ","ṝvṝ")\
            .replace("ṝuḷ","ṝvḷ")\
            .replace("ṝuḹ","ṝvḹ")\
            .replace("ṝue","ṝve")\
            .replace("ṝuo","ṝvo")\
            .replace("ḷuai","ḷvai")\
            .replace("ḷuau","ḷvau")\
            .replace("ḷua","ḷva")\
            .replace("ḷuā","ḷvā")\
            .replace("ḷui","ḷvi")\
            .replace("ḷuī","ḷvī")\
            .replace("ḷuu","ḷvu")\
            .replace("ḷuū","ḷvū")\
            .replace("ḷuṛ","ḷvṛ")\
            .replace("ḷuṝ","ḷvṝ")\
            .replace("ḷuḷ","ḷvḷ")\
            .replace("ḷuḹ","ḷvḹ")\
            .replace("ḷue","ḷve")\
            .replace("ḷuo","ḷvo")\
            .replace("ḹuai","ḹvai")\
            .replace("ḹuau","ḹvau")\
            .replace("ḹua","ḹva")\
            .replace("ḹuā","ḹvā")\
            .replace("ḹui","ḹvi")\
            .replace("ḹuī","ḹvī")\
            .replace("ḹuu","ḹvu")\
            .replace("ḹuū","ḹvū")\
            .replace("ḹuṛ","ḹvṛ")\
            .replace("ḹuṝ","ḹvṝ")\
            .replace("ḹuḷ","ḹvḷ")\
            .replace("ḹuḹ","ḹvḹ")\
            .replace("ḹue","ḹve")\
            .replace("ḹuo","ḹvo")\
            .replace("euai","evai")\
            .replace("euau","evau")\
            .replace("eua","eva")\
            .replace("euā","evā")\
            .replace("eui","evi")\
            .replace("euī","evī")\
            .replace("euu","evu")\
            .replace("euū","evū")\
            .replace("euṛ","evṛ")\
            .replace("euṝ","evṝ")\
            .replace("euḷ","evḷ")\
            .replace("euḹ","evḹ")\
            .replace("eue","eve")\
            .replace("euo","evo")\
            .replace("ouai","ovai")\
            .replace("ouau","ovau")\
            .replace("oua","ova")\
            .replace("ouā","ovā")\
            .replace("oui","ovi")\
            .replace("ouī","ovī")\
            .replace("ouu","ovu")\
            .replace("ouū","ovū")\
            .replace("ouṛ","ovṛ")\
            .replace("ouṝ","ovṝ")\
            .replace("ouḷ","ovḷ")\
            .replace("ouḹ","ovḹ")\
            .replace("oue","ove")\
            .replace("ouo","ovo")\
            .replace("aiṁai","aimai")\
            .replace("aiṁau","aimau")\
            .replace("aiṁa","aima")\
            .replace("aiṁā","aimā")\
            .replace("aiṁi","aimi")\
            .replace("aiṁī","aimī")\
            .replace("aiṁu","aimu")\
            .replace("aiṁū","aimū")\
            .replace("aiṁṛ","aimṛ")\
            .replace("aiṁṝ","aimṝ")\
            .replace("aiṁḷ","aimḷ")\
            .replace("aiṁḹ","aimḹ")\
            .replace("aiṁe","aime")\
            .replace("aiṁo","aimo")\
            .replace("auṁai","aumai")\
            .replace("auṁau","aumau")\
            .replace("auṁa","auma")\
            .replace("auṁā","aumā")\
            .replace("auṁi","aumi")\
            .replace("auṁī","aumī")\
            .replace("auṁu","aumu")\
            .replace("auṁū","aumū")\
            .replace("auṁṛ","aumṛ")\
            .replace("auṁṝ","aumṝ")\
            .replace("auṁḷ","aumḷ")\
            .replace("auṁḹ","aumḹ")\
            .replace("auṁe","aume")\
            .replace("auṁo","aumo")\
            .replace("aṁai","amai")\
            .replace("aṁau","amau")\
            .replace("aṁa","ama")\
            .replace("aṁā","amā")\
            .replace("aṁi","ami")\
            .replace("aṁī","amī")\
            .replace("aṁu","amu")\
            .replace("aṁū","amū")\
            .replace("aṁṛ","amṛ")\
            .replace("aṁṝ","amṝ")\
            .replace("aṁḷ","amḷ")\
            .replace("aṁḹ","amḹ")\
            .replace("aṁe","ame")\
            .replace("aṁo","amo")\
            .replace("āṁai","āmai")\
            .replace("āṁau","āmau")\
            .replace("āṁa","āma")\
            .replace("āṁā","āmā")\
            .replace("āṁi","āmi")\
            .replace("āṁī","āmī")\
            .replace("āṁu","āmu")\
            .replace("āṁū","āmū")\
            .replace("āṁṛ","āmṛ")\
            .replace("āṁṝ","āmṝ")\
            .replace("āṁḷ","āmḷ")\
            .replace("āṁḹ","āmḹ")\
            .replace("āṁe","āme")\
            .replace("āṁo","āmo")\
            .replace("iṁai","imai")\
            .replace("iṁau","imau")\
            .replace("iṁa","ima")\
            .replace("iṁā","imā")\
            .replace("iṁi","imi")\
            .replace("iṁī","imī")\
            .replace("iṁu","imu")\
            .replace("iṁū","imū")\
            .replace("iṁṛ","imṛ")\
            .replace("iṁṝ","imṝ")\
            .replace("iṁḷ","imḷ")\
            .replace("iṁḹ","imḹ")\
            .replace("iṁe","ime")\
            .replace("iṁo","imo")\
            .replace("īṁai","īmai")\
            .replace("īṁau","īmau")\
            .replace("īṁa","īma")\
            .replace("īṁā","īmā")\
            .replace("īṁi","īmi")\
            .replace("īṁī","īmī")\
            .replace("īṁu","īmu")\
            .replace("īṁū","īmū")\
            .replace("īṁṛ","īmṛ")\
            .replace("īṁṝ","īmṝ")\
            .replace("īṁḷ","īmḷ")\
            .replace("īṁḹ","īmḹ")\
            .replace("īṁe","īme")\
            .replace("īṁo","īmo")\
            .replace("uṁai","umai")\
            .replace("uṁau","umau")\
            .replace("uṁa","uma")\
            .replace("uṁā","umā")\
            .replace("uṁi","umi")\
            .replace("uṁī","umī")\
            .replace("uṁu","umu")\
            .replace("uṁū","umū")\
            .replace("uṁṛ","umṛ")\
            .replace("uṁṝ","umṝ")\
            .replace("uṁḷ","umḷ")\
            .replace("uṁḹ","umḹ")\
            .replace("uṁe","ume")\
            .replace("uṁo","umo")\
            .replace("ūṁai","ūmai")\
            .replace("ūṁau","ūmau")\
            .replace("ūṁa","ūma")\
            .replace("ūṁā","ūmā")\
            .replace("ūṁi","ūmi")\
            .replace("ūṁī","ūmī")\
            .replace("ūṁu","ūmu")\
            .replace("ūṁū","ūmū")\
            .replace("ūṁṛ","ūmṛ")\
            .replace("ūṁṝ","ūmṝ")\
            .replace("ūṁḷ","ūmḷ")\
            .replace("ūṁḹ","ūmḹ")\
            .replace("ūṁe","ūme")\
            .replace("ūṁo","ūmo")\
            .replace("ṛṁai","ṛmai")\
            .replace("ṛṁau","ṛmau")\
            .replace("ṛṁa","ṛma")\
            .replace("ṛṁā","ṛmā")\
            .replace("ṛṁi","ṛmi")\
            .replace("ṛṁī","ṛmī")\
            .replace("ṛṁu","ṛmu")\
            .replace("ṛṁū","ṛmū")\
            .replace("ṛṁṛ","ṛmṛ")\
            .replace("ṛṁṝ","ṛmṝ")\
            .replace("ṛṁḷ","ṛmḷ")\
            .replace("ṛṁḹ","ṛmḹ")\
            .replace("ṛṁe","ṛme")\
            .replace("ṛṁo","ṛmo")\
            .replace("ṝṁai","ṝmai")\
            .replace("ṝṁau","ṝmau")\
            .replace("ṝṁa","ṝma")\
            .replace("ṝṁā","ṝmā")\
            .replace("ṝṁi","ṝmi")\
            .replace("ṝṁī","ṝmī")\
            .replace("ṝṁu","ṝmu")\
            .replace("ṝṁū","ṝmū")\
            .replace("ṝṁṛ","ṝmṛ")\
            .replace("ṝṁṝ","ṝmṝ")\
            .replace("ṝṁḷ","ṝmḷ")\
            .replace("ṝṁḹ","ṝmḹ")\
            .replace("ṝṁe","ṝme")\
            .replace("ṝṁo","ṝmo")\
            .replace("ḷṁai","ḷmai")\
            .replace("ḷṁau","ḷmau")\
            .replace("ḷṁa","ḷma")\
            .replace("ḷṁā","ḷmā")\
            .replace("ḷṁi","ḷmi")\
            .replace("ḷṁī","ḷmī")\
            .replace("ḷṁu","ḷmu")\
            .replace("ḷṁū","ḷmū")\
            .replace("ḷṁṛ","ḷmṛ")\
            .replace("ḷṁṝ","ḷmṝ")\
            .replace("ḷṁḷ","ḷmḷ")\
            .replace("ḷṁḹ","ḷmḹ")\
            .replace("ḷṁe","ḷme")\
            .replace("ḷṁo","ḷmo")\
            .replace("ḹṁai","ḹmai")\
            .replace("ḹṁau","ḹmau")\
            .replace("ḹṁa","ḹma")\
            .replace("ḹṁā","ḹmā")\
            .replace("ḹṁi","ḹmi")\
            .replace("ḹṁī","ḹmī")\
            .replace("ḹṁu","ḹmu")\
            .replace("ḹṁū","ḹmū")\
            .replace("ḹṁṛ","ḹmṛ")\
            .replace("ḹṁṝ","ḹmṝ")\
            .replace("ḹṁḷ","ḹmḷ")\
            .replace("ḹṁḹ","ḹmḹ")\
            .replace("ḹṁe","ḹme")\
            .replace("ḹṁo","ḹmo")\
            .replace("eṁai","emai")\
            .replace("eṁau","emau")\
            .replace("eṁa","ema")\
            .replace("eṁā","emā")\
            .replace("eṁi","emi")\
            .replace("eṁī","emī")\
            .replace("eṁu","emu")\
            .replace("eṁū","emū")\
            .replace("eṁṛ","emṛ")\
            .replace("eṁṝ","emṝ")\
            .replace("eṁḷ","emḷ")\
            .replace("eṁḹ","emḹ")\
            .replace("eṁe","eme")\
            .replace("eṁo","emo")\
            .replace("oṁai","omai")\
            .replace("oṁau","omau")\
            .replace("oṁa","oma")\
            .replace("oṁā","omā")\
            .replace("oṁi","omi")\
            .replace("oṁī","omī")\
            .replace("oṁu","omu")\
            .replace("oṁū","omū")\
            .replace("oṁṛ","omṛ")\
            .replace("oṁṝ","omṝ")\
            .replace("oṁḷ","omḷ")\
            .replace("oṁḹ","omḹ")\
            .replace("oṁe","ome")\
            .replace("oṁo","omo")\
            .replace("aiṉai","ainai")\
            .replace("aiṉau","ainau")\
            .replace("aiṉa","aina")\
            .replace("aiṉā","ainā")\
            .replace("aiṉi","aini")\
            .replace("aiṉī","ainī")\
            .replace("aiṉu","ainu")\
            .replace("aiṉū","ainū")\
            .replace("aiṉṛ","ainṛ")\
            .replace("aiṉṝ","ainṝ")\
            .replace("aiṉḷ","ainḷ")\
            .replace("aiṉḹ","ainḹ")\
            .replace("aiṉe","aine")\
            .replace("aiṉo","aino")\
            .replace("auṉai","aunai")\
            .replace("auṉau","aunau")\
            .replace("auṉa","auna")\
            .replace("auṉā","aunā")\
            .replace("auṉi","auni")\
            .replace("auṉī","aunī")\
            .replace("auṉu","aunu")\
            .replace("auṉū","aunū")\
            .replace("auṉṛ","aunṛ")\
            .replace("auṉṝ","aunṝ")\
            .replace("auṉḷ","aunḷ")\
            .replace("auṉḹ","aunḹ")\
            .replace("auṉe","aune")\
            .replace("auṉo","auno")\
            .replace("aṉai","anai")\
            .replace("aṉau","anau")\
            .replace("aṉa","ana")\
            .replace("aṉā","anā")\
            .replace("aṉi","ani")\
            .replace("aṉī","anī")\
            .replace("aṉu","anu")\
            .replace("aṉū","anū")\
            .replace("aṉṛ","anṛ")\
            .replace("aṉṝ","anṝ")\
            .replace("aṉḷ","anḷ")\
            .replace("aṉḹ","anḹ")\
            .replace("aṉe","ane")\
            .replace("aṉo","ano")\
            .replace("āṉai","ānai")\
            .replace("āṉau","ānau")\
            .replace("āṉa","āna")\
            .replace("āṉā","ānā")\
            .replace("āṉi","āni")\
            .replace("āṉī","ānī")\
            .replace("āṉu","ānu")\
            .replace("āṉū","ānū")\
            .replace("āṉṛ","ānṛ")\
            .replace("āṉṝ","ānṝ")\
            .replace("āṉḷ","ānḷ")\
            .replace("āṉḹ","ānḹ")\
            .replace("āṉe","āne")\
            .replace("āṉo","āno")\
            .replace("iṉai","inai")\
            .replace("iṉau","inau")\
            .replace("iṉa","ina")\
            .replace("iṉā","inā")\
            .replace("iṉi","ini")\
            .replace("iṉī","inī")\
            .replace("iṉu","inu")\
            .replace("iṉū","inū")\
            .replace("iṉṛ","inṛ")\
            .replace("iṉṝ","inṝ")\
            .replace("iṉḷ","inḷ")\
            .replace("iṉḹ","inḹ")\
            .replace("iṉe","ine")\
            .replace("iṉo","ino")\
            .replace("īṉai","īnai")\
            .replace("īṉau","īnau")\
            .replace("īṉa","īna")\
            .replace("īṉā","īnā")\
            .replace("īṉi","īni")\
            .replace("īṉī","īnī")\
            .replace("īṉu","īnu")\
            .replace("īṉū","īnū")\
            .replace("īṉṛ","īnṛ")\
            .replace("īṉṝ","īnṝ")\
            .replace("īṉḷ","īnḷ")\
            .replace("īṉḹ","īnḹ")\
            .replace("īṉe","īne")\
            .replace("īṉo","īno")\
            .replace("uṉai","unai")\
            .replace("uṉau","unau")\
            .replace("uṉa","una")\
            .replace("uṉā","unā")\
            .replace("uṉi","uni")\
            .replace("uṉī","unī")\
            .replace("uṉu","unu")\
            .replace("uṉū","unū")\
            .replace("uṉṛ","unṛ")\
            .replace("uṉṝ","unṝ")\
            .replace("uṉḷ","unḷ")\
            .replace("uṉḹ","unḹ")\
            .replace("uṉe","une")\
            .replace("uṉo","uno")\
            .replace("ūṉai","ūnai")\
            .replace("ūṉau","ūnau")\
            .replace("ūṉa","ūna")\
            .replace("ūṉā","ūnā")\
            .replace("ūṉi","ūni")\
            .replace("ūṉī","ūnī")\
            .replace("ūṉu","ūnu")\
            .replace("ūṉū","ūnū")\
            .replace("ūṉṛ","ūnṛ")\
            .replace("ūṉṝ","ūnṝ")\
            .replace("ūṉḷ","ūnḷ")\
            .replace("ūṉḹ","ūnḹ")\
            .replace("ūṉe","ūne")\
            .replace("ūṉo","ūno")\
            .replace("ṛṉai","ṛnai")\
            .replace("ṛṉau","ṛnau")\
            .replace("ṛṉa","ṛna")\
            .replace("ṛṉā","ṛnā")\
            .replace("ṛṉi","ṛni")\
            .replace("ṛṉī","ṛnī")\
            .replace("ṛṉu","ṛnu")\
            .replace("ṛṉū","ṛnū")\
            .replace("ṛṉṛ","ṛnṛ")\
            .replace("ṛṉṝ","ṛnṝ")\
            .replace("ṛṉḷ","ṛnḷ")\
            .replace("ṛṉḹ","ṛnḹ")\
            .replace("ṛṉe","ṛne")\
            .replace("ṛṉo","ṛno")\
            .replace("ṝṉai","ṝnai")\
            .replace("ṝṉau","ṝnau")\
            .replace("ṝṉa","ṝna")\
            .replace("ṝṉā","ṝnā")\
            .replace("ṝṉi","ṝni")\
            .replace("ṝṉī","ṝnī")\
            .replace("ṝṉu","ṝnu")\
            .replace("ṝṉū","ṝnū")\
            .replace("ṝṉṛ","ṝnṛ")\
            .replace("ṝṉṝ","ṝnṝ")\
            .replace("ṝṉḷ","ṝnḷ")\
            .replace("ṝṉḹ","ṝnḹ")\
            .replace("ṝṉe","ṝne")\
            .replace("ṝṉo","ṝno")\
            .replace("ḷṉai","ḷnai")\
            .replace("ḷṉau","ḷnau")\
            .replace("ḷṉa","ḷna")\
            .replace("ḷṉā","ḷnā")\
            .replace("ḷṉi","ḷni")\
            .replace("ḷṉī","ḷnī")\
            .replace("ḷṉu","ḷnu")\
            .replace("ḷṉū","ḷnū")\
            .replace("ḷṉṛ","ḷnṛ")\
            .replace("ḷṉṝ","ḷnṝ")\
            .replace("ḷṉḷ","ḷnḷ")\
            .replace("ḷṉḹ","ḷnḹ")\
            .replace("ḷṉe","ḷne")\
            .replace("ḷṉo","ḷno")\
            .replace("ḹṉai","ḹnai")\
            .replace("ḹṉau","ḹnau")\
            .replace("ḹṉa","ḹna")\
            .replace("ḹṉā","ḹnā")\
            .replace("ḹṉi","ḹni")\
            .replace("ḹṉī","ḹnī")\
            .replace("ḹṉu","ḹnu")\
            .replace("ḹṉū","ḹnū")\
            .replace("ḹṉṛ","ḹnṛ")\
            .replace("ḹṉṝ","ḹnṝ")\
            .replace("ḹṉḷ","ḹnḷ")\
            .replace("ḹṉḹ","ḹnḹ")\
            .replace("ḹṉe","ḹne")\
            .replace("ḹṉo","ḹno")\
            .replace("eṉai","enai")\
            .replace("eṉau","enau")\
            .replace("eṉa","ena")\
            .replace("eṉā","enā")\
            .replace("eṉi","eni")\
            .replace("eṉī","enī")\
            .replace("eṉu","enu")\
            .replace("eṉū","enū")\
            .replace("eṉṛ","enṛ")\
            .replace("eṉṝ","enṝ")\
            .replace("eṉḷ","enḷ")\
            .replace("eṉḹ","enḹ")\
            .replace("eṉe","ene")\
            .replace("eṉo","eno")\
            .replace("oṉai","onai")\
            .replace("oṉau","onau")\
            .replace("oṉa","ona")\
            .replace("oṉā","onā")\
            .replace("oṉi","oni")\
            .replace("oṉī","onī")\
            .replace("oṉu","onu")\
            .replace("oṉū","onū")\
            .replace("oṉṛ","onṛ")\
            .replace("oṉṝ","onṝ")\
            .replace("oṉḷ","onḷ")\
            .replace("oṉḹ","onḹ")\
            .replace("oṉe","one")\
            .replace("oṉo","ono")\
            .replace("iai","yai")\
            .replace("iau","yau")\
            .replace("ia","ya")\
            .replace("iā","yā")\
            .replace("ii","ī")\
            .replace("iī","ī")\
            .replace("iu","yu")\
            .replace("iū","yū")\
            .replace("iṛ","yṛ")\
            .replace("iṝ","yṝ")\
            .replace("iḷ","yḷ")\
            .replace("iḹ","yḹ")\
            .replace("ie","ye")\
            .replace("io","yo")\
            .replace("uai","vai")\
            .replace("uau","vau")\
            .replace("ua","va")\
            .replace("uā","vā")\
            .replace("ui","vi")\
            .replace("uī","vī")\
            .replace("uu","ū")\
            .replace("uū","ū")\
            .replace("uṛ","vṛ")\
            .replace("uṝ","vṝ")\
            .replace("uḷ","vḷ")\
            .replace("uḹ","vḹ")\
            .replace("ue","ve")\
            .replace("uo","vo")\
            .replace("ṁai","mai")\
            .replace("ṁau","mau")\
            .replace("ṁa","ma")\
            .replace("ṁā","mā")\
            .replace("ṁi","mi")\
            .replace("ṁī","mī")\
            .replace("ṁu","mu")\
            .replace("ṁū","mū")\
            .replace("ṁṛ","mṛ")\
            .replace("ṁṝ","mṝ")\
            .replace("ṁḷ","mḷ")\
            .replace("ṁḹ","mḹ")\
            .replace("ṁe","me")\
            .replace("ṁo","mo")\
            .replace("ṉai","nai")\
            .replace("ṉau","nau")\
            .replace("ṉa","na")\
            .replace("ṉā","nā")\
            .replace("ṉi","ni")\
            .replace("ṉī","nī")\
            .replace("ṉu","nu")\
            .replace("ṉū","nū")\
            .replace("ṉṛ","nṛ")\
            .replace("ṉṝ","nṝ")\
            .replace("ṉḷ","nḷ")\
            .replace("ṉḹ","nḹ")\
            .replace("ṉe","ne")\
            .replace("ṉo","no")\
            .replace("īai","yai")\
            .replace("īau","yau")\
            .replace("īa","ya")\
            .replace("īā","yā")\
            .replace("īi","ī")\
            .replace("īī","ī")\
            .replace("īu","yu")\
            .replace("īū","yū")\
            .replace("īṛ","yṛ")\
            .replace("īṝ","yṝ")\
            .replace("īḷ","yḷ")\
            .replace("īḹ","yḹ")\
            .replace("īe","ye")\
            .replace("īo","yo")\
            .replace("ūai","vai")\
            .replace("ūau","vau")\
            .replace("ūa","va")\
            .replace("ūā","vā")\
            .replace("ūi","vi")\
            .replace("ūī","vī")\
            .replace("ūu","ū")\
            .replace("ūū","ū")\
            .replace("ūṛ","vṛ")\
            .replace("ūṝ","vṝ")\
            .replace("ūḷ","vḷ")\
            .replace("ūḹ","vḹ")\
            .replace("ūe","ve")\
            .replace("ūo","vo")\
            .replace("hṉt","hat")\
            .replace("gṁc","gac")
    )

vowels = ["ai"]+["au"]+list("aāiīuūṛṝḷḹeoṁṉ")